'use client';

import { useEffect, useRef, useState } from 'react';

type Source = 'microphone' | 'impulse' | 'tone' | 'chirp' | 'noise' | 'sweep';
const clamp = (n:number,min:number,max:number)=>Math.min(max,Math.max(min,n));
const fmtHz=(n:number)=>n>=1000?`${(n/1000).toFixed(n>=10000?0:1)} kHz`:`${Math.round(n)} Hz`;

function draw(canvas:HTMLCanvasElement,time:Float32Array,freq:Float32Array,sr:number,history:number[]){
 const ctx=canvas.getContext('2d'); if(!ctx)return; const dpr=window.devicePixelRatio||1,w=Math.max(1,canvas.clientWidth*dpr),h=Math.max(1,canvas.clientHeight*dpr);
 if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h} ctx.clearRect(0,0,w,h);ctx.fillStyle='#050b10';ctx.fillRect(0,0,w,h);
 ctx.strokeStyle='#16303c';ctx.lineWidth=1;for(let i=1;i<5;i++){const y=h*i/5;ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}
 ctx.strokeStyle='#67e8f9';ctx.lineWidth=2;ctx.beginPath();for(let x=0;x<w;x++){const i=Math.min(time.length-1,Math.floor(x/w*time.length));const y=h*.28-time[i]*h*.22;x?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.stroke();
 ctx.strokeStyle='#a78bfa';ctx.beginPath();const ny=sr/2;for(let x=0;x<w;x++){const f=20*Math.pow(1000,x/Math.max(1,w-1));const bin=Math.min(freq.length-1,Math.max(1,Math.floor(f/ny*freq.length)));const db=freq[bin];const mag=clamp((db+100)/100,0,1);const y=h*.96-mag*h*.52;x?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.stroke();
 ctx.strokeStyle='#334155';ctx.beginPath();history.forEach((v,i)=>{const x=i/Math.max(1,history.length-1)*w,y=h*.72-v*h*.3;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();
 ctx.fillStyle='#64748b';ctx.font=`${11*dpr}px ui-monospace`;ctx.fillText('WAVEFORM',12,18*dpr);ctx.fillText('LOG SPECTRUM · 20 Hz — 20 kHz',12,h-10*dpr);ctx.fillText('ENERGY HISTORY',12,h*.70);
}

function synth(ctx:AudioContext,kind:Source,freq:number,dur:number){
 const n=Math.floor(ctx.sampleRate*dur),b=ctx.createBuffer(1,n,ctx.sampleRate),d=b.getChannelData(0);
 for(let i=0;i<n;i++){const t=i/ctx.sampleRate,env=Math.exp(-t*5),r=Math.random()*2-1;let v=0;
  if(kind==='impulse')v=i<ctx.sampleRate*.001?.8*(1-i/(ctx.sampleRate*.001)):0;
  else if(kind==='tone')v=Math.sin(2*Math.PI*freq*t)*.28;
  else if(kind==='chirp'){const f0=20,f1=20000,k=(f1-f0)/dur;v=Math.sin(2*Math.PI*(f0*t+.5*k*t*t))*.25*env}
  else if(kind==='sweep'){const f0=20,f1=20000,k=Math.log(f1/f0)/dur;v=Math.sin(2*Math.PI*f0*(Math.exp(k*t)-1)/k)*.25*env}
  else v=r*.2*env; d[i]=v;
 } return b;
}

export default function Home(){
 const canvas=useRef<HTMLCanvasElement>(null),audio=useRef<AudioContext|null>(null),an=useRef<AnalyserNode|null>(null),stream=useRef<MediaStream|null>(null),node=useRef<AudioBufferSourceNode|null>(null),raf=useRef<number|null>(null),history=useRef<number[]>([]),lastUi=useRef(0);
 const [source,setSource]=useState<Source>('microphone'),[running,setRunning]=useState(false),[threshold,setThreshold]=useState(.62),[gain,setGain]=useState(.12),[tone,setTone]=useState(1000),[peak,setPeak]=useState(0),[rms,setRms]=useState(0),[centroid,setCentroid]=useState(0),[flux,setFlux]=useState(0),[snr,setSnr]=useState(0),[bands,setBands]=useState([0,0,0,0,0]),[status,setStatus]=useState('Ready — local laboratory mode.'),[events,setEvents]=useState(0);
 const previous=useRef<Float32Array|null>(null);
 useEffect(()=>()=>cleanup(),[]);
 function cleanup(){if(raf.current)cancelAnimationFrame(raf.current);stream.current?.getTracks().forEach(t=>t.stop());try{node.current?.stop()}catch{}try{node.current?.disconnect()}catch{}node.current=null;stream.current=null;setRunning(false)}
 async function ensure(){if(!audio.current){const C=window.AudioContext||(window as typeof window&{webkitAudioContext:typeof AudioContext}).webkitAudioContext;audio.current=new C()}await audio.current.resume();return audio.current}
 function loop(){const a=an.current,c=canvas.current;if(!a||!c)return;const td=new Float32Array(a.fftSize),fd=new Float32Array(a.frequencyBinCount);a.getFloatTimeDomainData(td);a.getFloatFrequencyData(fd);let p=0,e=0,total=0,wt=0;for(const v of td){p=Math.max(p,Math.abs(v));e+=v*v}const mags=new Float32Array(fd.length);let diff=0;for(let i=1;i<fd.length;i++){const m=Math.pow(10,fd[i]/20);mags[i]=m;diff+=Math.max(0,m-(previous.current?.[i]??m));const f=i*a.context.sampleRate/(2*fd.length);total+=m;wt+=m*f}previous.current=mags;const rr=Math.sqrt(e/td.length),cf=total?wt/total:0,db=20*Math.log10(Math.max(rr,1e-7)),estimatedSnr=clamp(db+60,0,60);const edges=[20,100,300,1000,3000,20000],vals=edges.slice(0,-1).map((lo,j)=>{let sum=0;for(let i=1;i<fd.length;i++){const f=i*a.context.sampleRate/(2*fd.length);if(f>=lo&&f<edges[j+1])sum+=mags[i]}return sum});const max=Math.max(...vals,1e-9),norm=vals.map(v=>20*Math.log10(Math.max(v/max,1e-9)));history.current=[...history.current.slice(-119),rr];const confidence=clamp((p*.75+rr*2.5)*.5,0,1);const now=performance.now();if(now-lastUi.current>80){setPeak(p);setRms(rr);setCentroid(cf);setFlux(diff);setSnr(estimatedSnr);setBands(norm);if(confidence>=threshold)setEvents(x=>x+1);lastUi.current=now}draw(c,td,fd,a.context.sampleRate,history.current);raf.current=requestAnimationFrame(loop)}
 async function start(){try{cleanup();history.current=[];previous.current=null;const C=await ensure(),a=C.createAnalyser();a.fftSize=4096;a.smoothingTimeConstant=.06;an.current=a;if(source==='microphone'){const s=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:false,noiseSuppression:false,autoGainControl:false},video:false});stream.current=s;C.createMediaStreamSource(s).connect(a);setStatus('Microphone analysis active. Processing stays in this browser.');setRunning(true);loop();return}const b=synth(C,source,tone,source==='chirp'||source==='sweep'?4:2),bs=C.createBufferSource(),g=C.createGain(),lim=C.createDynamicsCompressor();g.gain.value=gain;lim.threshold.value=-6;lim.knee.value=12;lim.ratio.value=12;lim.attack.value=.003;lim.release.value=.12;bs.buffer=b;bs.connect(g).connect(lim).connect(a);lim.connect(C.destination);node.current=bs;bs.onended=()=>{setRunning(false);setStatus('Playback complete. Results remain local to this session.');};bs.start();setStatus('Synthetic playback + analysis active.');setRunning(true);loop()}catch{setStatus('Audio unavailable or microphone permission was denied.')}}
 function exportResults(){const payload={app:'Acoustic Lab Alpha',mode:'local laboratory',timestamp:new Date().toISOString(),source,threshold,gain,tone,peak,rms,centroid,flux,snr,bands,events};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`acoustic-lab-${Date.now()}.json`;a.click();URL.revokeObjectURL(url);setStatus('Measurement snapshot exported locally as JSON.')}
 const conf=clamp((peak*.75+rms*2.5)*.5,0,1),state=conf>=threshold?'SIGNATURE-LIKE':'BACKGROUND / BELOW THRESHOLD';
 return <main className='shell'><section className='hero'><div><p className='eyebrow'>ACOUSTIC LAB · ALPHA</p><h1>Sound as signal.</h1><p className='lede'>A local instrument for studying acoustic waveforms, spectral structure and detector behaviour — with reproducible synthetic signals and microphone analysis.</p></div><div className='pill'>SAFE LAB MODE</div></section><section className='grid'>
 <article className='panel wide'><div className='panelHead'><div><span className='label'>LIVE ANALYSIS</span><h2>{state}</h2></div><span className='mono'>{(conf*100).toFixed(0)}%</span></div><canvas ref={canvas} className='scope'/><div className='metrics'><div><span>PEAK</span><strong>{peak.toFixed(3)}</strong></div><div><span>RMS</span><strong>{rms.toFixed(3)}</strong></div><div><span>CENTROID</span><strong>{centroid?fmtHz(centroid):'—'}</strong></div><div><span>SPECTRAL FLUX</span><strong>{flux.toFixed(3)}</strong></div><div><span>ENERGY SNR*</span><strong>{snr.toFixed(1)} dB</strong></div><div><span>EVENT COUNT</span><strong>{events}</strong></div></div></article>
 <article className='panel'><span className='label'>SIGNAL SOURCE</span><h3>Laboratory input</h3><div className='seg'>{(['microphone','impulse','tone','chirp','noise','sweep'] as Source[]).map(s=><button key={s} className={source===s?'active':''} onClick={()=>!running&&setSource(s)} disabled={running}>{s[0].toUpperCase()+s.slice(1)}</button>)}</div>{source==='tone'&&<label>Frequency<input type='range' min='20' max='20000' step='10' value={tone} onChange={e=>setTone(+e.target.value)}/><b>{tone.toLocaleString()} Hz</b></label>}{source!=='microphone'&&<label>Playback gain<input type='range' min='0' max='.5' step='.01' value={gain} onChange={e=>setGain(+e.target.value)}/><b>{gain.toFixed(2)}</b></label>}<label>Detector threshold<input type='range' min='.05' max='.95' step='.01' value={threshold} onChange={e=>setThreshold(+e.target.value)}/><b>{threshold.toFixed(2)}</b></label><div className='actions'><button className='primary' onClick={running?cleanup:start}>{running?(source==='microphone'?'Stop analysis':'Stop playback'):(source==='microphone'?'Start analysis':'Play & analyse')}</button><button className='secondary' onClick={exportResults}>Export measurement JSON</button></div><p className='status'>{status}</p></article>
 <article className='panel'><span className='label'>SPECTRAL BANDS</span><h3>Relative band energy</h3><div className='bandGrid'>{['20–100 Hz','100–300 Hz','300 Hz–1 kHz','1–3 kHz','3–20 kHz'].map((x,i)=><div key={x}><span>{x}</span><strong>{bands[i]?.toFixed(1)??'0.0'} dB</strong><i><em style={{width:`${clamp((bands[i]+60)/60*100,0,100)}%`}}/></i></div>)}</div><p>*SNR is an energy-derived research indicator, not a calibrated acoustic measurement.</p></article>
 <article className='panel'><span className='label'>FREQUENCY LAB</span><h3>20 Hz → 20 kHz</h3><p>Wide conventional audible-band analysis. This is a research range, not a claim about any proprietary microphone response.</p><div className='band'><span>20 Hz</span><span>100 Hz</span><span>1 kHz</span><span>10 kHz</span><span>20 kHz</span></div><div className='note'>Synthetic signals are generated locally. Microphone input is analysed locally and is not uploaded.</div></article>
 <article className='panel'><span className='label'>MEASUREMENT ENGINE</span><h3>Feature stack</h3><p>Alpha now combines peak amplitude, RMS energy, spectral centroid, spectral flux, relative band energy and an event counter. UI updates are throttled while the canvas remains real-time for smoother performance.</p><div className='pipeline'><span>INPUT</span><i>→</i><span>FFT 4096</span><i>→</i><span>FEATURES</span><i>→</i><span>THRESHOLD</span><i>→</i><span>RESULT</span></div></article>
 <article className='panel wide'><span className='label'>EXPERIMENT DESIGN</span><h3>Reproducible research, not device targeting</h3><div className='research'><div><b>1</b><span>Generate a controlled signal</span></div><div><b>2</b><span>Measure its feature profile</span></div><div><b>3</b><span>Vary threshold and noise</span></div><div><b>4</b><span>Export the measurement</span></div></div><div className='note'>Designed for acoustic research and detector evaluation. No network discovery, remote transmission, surveillance-device control or live-system interaction is implemented.</div></article>
 </section></main>
}